 a = """
	SELECT lkp_MDI_CLAIM_TXN_ID, SRC_CLD_KEY FROM (
		select A.MDI_CLAIM_TXN_ID as lkp_MDI_CLAIM_TXN_ID,
           A.SRC_CLD_KEY as SRC_CLD_KEY,
		   ROW_NUMBER() OVER(PARTITION BY A.SRC_CLD_KEY ORDER BY A.MDI_CLAIM_TXN_ID DESC) AS RN
		from MDI_CLD_SRC_KEY_LU_PREV A
			where SUBSTR(A.SRC_CLD_KEY, 1, 6) in
				(SELECT DISTINCT REBATE_YEAR_QTR from STG_MDI_CLD_USR_TXN)
				) X WHERE RN = 1
	"""
 